import { createRoot } from "react-dom/client";
import App from "./App";
import "./vigil-reference-metadata";
import "./index.css";
import "./dark-appearance.css";
import "./home-ux.css";
import "./vigil-reading-legibility.css";
import "./constitution-catalogue-ux.css";
import "./sitewide-visual-closure.css";
import "./vigil-reference-datasets.css";
import "./vigil-public-consistency.css";
import "./vigil-page-shell.css";
import "./public-development-status.css";
import "./vigil-external-baseline.css";
import "./vigil-reference-list-cleanup.css";
import "./vigil-baseline-clause-collapse-fix.css";
import "./vigil-mobile-evidence-fix.css";
import "./sitewide-typography-floor.css";
import "./vigil-evidence-reading-hierarchy.css";
import "./vigil-case-file-dossier.css";
import "./vigil-case-file-polish.css";

createRoot(document.getElementById("root")!).render(<App />);