import { createRoot } from "react-dom/client";
import App from "./App";
import "./vigil-reference-metadata";
import "./vigil-observatory-surface-cleanup";
import "./index.css";
import "./dark-appearance.css";
import "./home-ux.css";
import "./vigil-reading-legibility.css";
import "./constitution-catalogue-ux.css";
import "./sitewide-visual-closure.css";
import "./vigil-reference-datasets.css";
import "./vigil-public-consistency.css";
import "./vigil-page-shell.css";
import "./public-development-status.css";
import "./vigil-external-baseline.css";
import "./vigil-reference-list-cleanup.css";
import "./vigil-baseline-clause-collapse-fix.css";
import "./vigil-mobile-evidence-fix.css";
import "./sitewide-typography-floor.css";
import "./vigil-evidence-reading-hierarchy.css";
import "./vigil-case-file-dossier.css";
import "./vigil-case-file-polish.css";
import "./vigil-exemplar-mixed-execution.css";
import "./vigil-incident-severity-refinement.css";
import "./vigil-harm-assessment-cleanup.css";
import "./vigil-assessment-provenance-cleanup.css";
import "./vigil-classification-table.css";
import "./vigil-case-library-simplify.css";
import "./vigil-observatory-surface-cleanup.css";
import "./governance-rail-refinements.css";
import "./vigil-deterministic-report.css";
import "./vigil-case-file-narrative-cards.css";
import "./about-page-polish.css";
import "./public-surface-responsive-cleanup.css";

createRoot(document.getElementById("root")!).render(<App />);